### ISSUE TITLE
Professional contact

### ISSUE THREAD

**Issue by uepoch** [asticode/go-astibob#1]
Hello Asticode, I must say i'm quite a big fan of your projects ( go-astitools saved my CI from burning last week ), I would love to send you littles bricks of nuts-juice by mail 

Do you have any contact method ?

I heard you were quite the shit in India

**Comment by asticode** [comment]
Hello @uepoch,

You seem like quite the shit too on the Internet. May I know which package saved your CI from burning last week?

You should have a received an encrypted message on your Skype.

Bite
Cheers
