### ISSUE TITLE
Can't connect using localhost (can connect with 127.0.0.1)

### ISSUE THREAD

**Issue by ajkeeton** [asticode/go-astibob#2]
The docs say 127.0.0.1, but localhost is synonymous. It turns out using localhost causes the websocket upgrader check in Gorilla to fail due to the origin ("localhost:6969" != "127.0.0.1:6969").

So it's not a bug, but I'm sure I won't be the last person who gets snagged! Might be convenient to have a note in the docs or a workaround.

**Comment by asticode** [comment]
@ajkeeton very nice find! I'll check whether there's a fix to it.

Cheers for using the project :)

**Comment by asticode** [comment]
@ajkeeton actually I've run the examples with `localhost` instead of `127.0.0.1` and it worked properly. Did you update the URLs both in Bob and all the brain's configurations?

Bob configuration would look like:

```go
astibob.Configuration{
		BrainsServer: astibob.ServerConfiguration{
			ListenAddr: "localhost:6970",
			Password:   "admin",
			Username:   "admin",
		},
		ClientsServer: astibob.ServerConfiguration{
			ListenAddr: "localhost:6969",
			Password:   "admin",
			Username:   "admin",
		},
		ResourcesDirectory: "resources",
	}
```

And brain configuration would look like:

```go
astibrain.Configuration{
		Name: "Brain #1",
		Websocket: astibrain.WebsocketConfiguration{
			Password: "admin",
			URL:      "ws://localhost:6970/websocket",
			Username: "admin",
		},
	}
```

This should work properly.

**Comment by ajkeeton** [comment]
Thanks :) 

Once I figured out what was happening, I just pointed my browser to 127.0.0.1 instead of changing the configurations

**Comment by asticode** [comment]
Cheers
