### ISSUE TITLE
Error when i run demo

### ISSUE THREAD

**Issue by tdaron** [asticode/go-astibob#3]
Hey ! I've an error when i run demo

13:12 $ go run demo/bob/main.go -v

./server_brains.go:58:35: cannot use s.adaptWebsocketClient (type func(*astiws.Client)) as type astiws.ClientAdapter in argument to s.server.ws.ServeHTTP
./server_clients.go:153:35: cannot use s.adaptWebsocketClient (type func(*astiws.Client)) as type astiws.ClientAdapter in argument to s.server.ws.ServeHTTP
./server_clients.go:212:13: c.HandlePing undefined (type *astiws.Client has no field or method HandlePing)

**Comment by asticode** [comment]
@Kaporos thanks for letting me know. Should be all good now. Can you confirm ?
